TRY extending the -a argument by acceptor kind
Trying out -a [name=][kind,][listen_address[,PROTO|,option=value,...]]

The problem here is that

	foo,bar

could mean

	kind=foo, listen_address=bar

or

	listen_address=foo, PROTO=bar

and, because of backwards compatibility, the error message might be confusing:

	$ /tmp/sbin/varnishd -a foo=xxx,@foo -b @a -n /tmp/t
	Error: Unknown protocol '@foo'

So my question is: Do we want this for simplicity, or rather a new argument
name, for example -A ?